#!/usr/bin/env python

import os, sys
from bottle import Bottle, request
#from bottle import hook, response, route, run, template

import query

#cmd_folder = os.path.dirname(os.path.abspath(__file__))
#if cmd_folder not in sys.path:
  #sys.path.insert(0, cmd_folder)

@hook('after_request')
def enable_cors():
  response.headers['Access-Control-Allow-Origin'] = '*'

application = Bottle()
app = application

#--------------- Define needed routes -------------------

@app.route('/')
def index():
  return  '<p>Data server for the <a href="http://data.msulocalgov.net">Montana Local Government Center Data Portal</a></p>'

@app.route('/hello')
@app.route('/hello/<name>')
def greet(name='Stranger'):
  return 'Hello there, %s?' % name

@route('/data/<format>/<type>')
@route('/data/<format>/<type>/<name>')
@route('/data/<format>/<type>/<name>/year/<year>')
@route('/data/<format>/<type>/<name>/year/<year>/fields/<fields>')
@route('/data/<format>/<type>/<name>/fields/<fields>')
def get_the_data(format='', type='', name='', year='', fields=''):
	data = query_lgc.get_data(format, type, name, year, fields)
	return data

#---------- Main method for local developement ----------

if __name__ == '__main__':
  bottle.debug(True)
  #run(reloader=True)
