#!/usr/bin/env python

import os, json
from bottle import Bottle, request
try:
  import pymysql
  pymysql.install_as_MySQLdb()
except ImportError:
  pass

myhost = os.environ['OPENSHIFT_MYSQL_DB_HOST']
myport = os.environ['OPENSHIFT_MYSQL_DB_PORT']
myuser = os.environ['OPENSHIFT_MYSQL_DB_USERNAME']
mypw = os.environ['OPENSHIFT_MYSQL_DB_PASSWORD']

application = Bottle()
app = application

@app.route('/')
def index():
  return  '''
              <p><a href="/parks">All Parks</a></p>
              <p><a href="/parks/park">Query by Park ID</a></p>
              <p><a href="/parks/name">Query by Park Name</a></p>
              <p><a href="/parks/near">Query by Coordinates</a></p>
              <p><a href="/parks/name/near">Query by Park Name & Coordinates</a></p>
          '''

@app.route('/api')
@app.route('/api/<name>')
def api(name='Stranger'):
  conn = pymysql.connect(host=myhost, user=myuser, passwd=mypw, db="lgc", cursorclass=pymysql.cursors.DictCursor)
  sql = 'SELECT count(*) FROM info'
  cursor = conn.cursor()
  cursor.execute(sql)
  rows = cursor.fetchall()
  return rows[0]

@app.route('/hello')
@app.route('/hello/<name>')
def greet(name='Stranger'):
  return 'Hello there there Mr. %s, how are you?' % name

