#!/usr/bin/env python

import os, json
from bottle import Bottle, request

host = os.environ['OPENSHIFT_MYSQL_DB_HOST']
port = os.environ['OPENSHIFT_MYSQL_DB_PORT']
user = os.environ['OPENSHIFT_MYSQL_DB_USERNAME']
pw = os.environ['OPENSHIFT_MYSQL_DB_PASSWORD']

application = Bottle()
app = application

@app.route('/')
def index():
  return  '''
              <p><a href="/parks">All Parks</a></p>
              <p><a href="/parks/park">Query by Park ID</a></p>
              <p><a href="/parks/name">Query by Park Name</a></p>
              <p><a href="/parks/near">Query by Coordinates</a></p>
              <p><a href="/parks/name/near">Query by Park Name & Coordinates</a></p>
          '''

@app.route('/hello')
@app.route('/hello/<name>')
def greet(name='Stranger'):
  return 'Hello %s, how are you?' % name

@app.route('/api')
def api(name='Stranger'):
  return 'hey'


